version: '3'
services:
  db:
    image: postgres:9.6
    restart: always
    volumes:
      - ./tmp/docker/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  cache:
    image: redis:3.2
    restart: always
    volumes:
      - ./tmp/docker/cache:/data
    ports:
      - '6379:6379'
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
      - cache
