cache_store:
  redis:
    namespace: 'cache'
    url: <%= ENV.fetch('REDIS_URL') { 'redis://localhost:6379' } %>/0
session_store:
  key: _session
  serializer: json
  redis:
    expire_after: <%= 1.day %>
    key_prefix: 'session:'
    url: <%= ENV.fetch('REDIS_URL') { 'redis://localhost:6379' } %>/1
carrierwave:
  storage: file
